steps:
  - imports:
      align: group
      list_align: after_alias
      long_list_align: new_line
      empty_list_align: right_after
      list_padding: module_name
  - language_pragmas:
      style: vertical
      remove_redundant: true
  - trailing_whitespace: {}
columns: 80
language_extensions:
  - MultiParamTypeClasses
  - FlexibleContexts
  - ExplicitForAll
  - DataKinds
